star:
  check-servers: true
  servers:
    default:
      host: definesys
      port: 30156
      key: star-key
#    local:
#      host: localhost
#      port: 30180
#      key: star-key

logging:
  level:
    star: debug
  group:
    star: com.isxcode.star
