application:
  version: 1.2.0

spring:
  profiles:
    active: star
  banner:
    location: classpath:banner.txt

server:
  port: 30156
  servlet:
    context-path: /spark-star

star:
  secret: star-key
