name: deploy website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
            host: isxcode.com
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            rm: true
            source: "./docs"
            target: "/data/spark-star/"
