
### 执行sparkSql查询
POST http://localhost:8080/executeSql
Content-Type: application/json

{
    "sparkSql": "CREATE TEMPORARY VIEW view_table \n USING org.apache.spark.sql.jdbc \n OPTIONS ( driver 'com.mysql.cj.jdbc.Driver',url 'jdbc:mysql://localhost:3306/ispong_db',user 'root',password 'ispong123',dbtable 'users'); insert into view_table (username ,age) values('ispong',100);"
}

### 执行mysql->mysql
POST http://localhost:8080/executeSql
Content-Type: application/json

{
    "sparkSql": "CREATE TEMPORARY VIEW view_table \n USING org.apache.spark.sql.jdbc \n OPTIONS ( driver 'com.mysql.cj.jdbc.Driver',url 'jdbc:mysql://localhost:3306/ispong_db',user 'root',password 'ispong123',dbtable 'users');CREATE TEMPORARY VIEW view_table_sink \n USING org.apache.spark.sql.jdbc \n OPTIONS ( driver 'com.mysql.cj.jdbc.Driver',url 'jdbc:mysql://localhost:3306/ispong_db',user 'root',password 'ispong123',dbtable 'users_sink'); insert into view_table_sink select * from view_table;"
}

### 获取yarn作业状态
POST http://localhost:8080/getStatus
Content-Type: application/json

{
  "applicationId": "application_1676601640542_0026"
}

### 获取作业日志
POST http://localhost:8080/getLog
Content-Type: application/json

{
    "applicationId": "application_1676601640542_0026"
}

### 查询返回值
POST http://localhost:8080/getData
Content-Type: application/json

{
    "applicationId": "application_1676601640542_0025"
}

### 停止作业
POST http://localhost:8080/stopJob
Content-Type: application/json

{
    "applicationId": "application_1676601640542_0023"
}

### 测试star session
POST http://localhost:30156/spark-star/executeSessionSql
Content-Type: application/json
star-key: star-key

{
    "sql": "select * from users"
}

### 测试环境
GET http://localhost:8080/checkServerEnv?serverId=123

### 安装spark-star
GET http://localhost:8080/installStar?serverId=123
